import deque_double_linkedlist as dll

obj = dll.DequeDoubleLinkedList()

obj.add(21)
obj.add(22)
obj.add(23)
obj.add(24)
obj.add(25)

obj.show()
print(f'top value = {obj.peek()}')
print(f'remove top value = {obj.remove()}')
obj.show()
print(f'top value = {obj.peek()}')
print(f'remove top value = {obj.remove()}')
obj.show()
print(f'top value = {obj.peek()}')
print(f'remove top value = {obj.remove()}')
obj.show()
print(f'top value = {obj.peek()}')
print(f'remove top value = {obj.remove()}')
obj.show()
print(f'top value = {obj.peek()}')
print(f'top value = {obj.peek()}')
print(f'remove top value = {obj.remove()}')
obj.show()
print(f'top value = {obj.peek()}')

obj.addFirst(20)
obj.show()
print(f'top value = {obj.peek()}')

print(f'***************')
obj.add(21)
obj.add(22)
obj.add(23)
obj.add(24)
obj.add(25)
obj.show()
print(f'top value = {obj.peek()}')


obj.addFirst(19)
obj.show()
print(f'top value = {obj.peek()}')

print(f'remove last value = {obj.removeLast()}')
obj.show()
print(f'remove last value = {obj.removeLast()}')
obj.show()
print(f'remove last value = {obj.removeLast()}')
obj.show()
print(f'remove last value = {obj.removeLast()}')
obj.show()
print(f'remove last value = {obj.removeLast()}')
obj.show()
print(f'remove last value = {obj.removeLast()}')
obj.show()
print(f'remove last value = {obj.removeLast()}')
obj.show()

obj.addFirst(20)
obj.show()
obj.show()
print(f'top value = {obj.peek()}')

print(f'*************** last')
obj.add(21)
obj.add(22)
obj.add(23)
obj.add(24)
obj.add(25)
obj.show()
print(f'top value = {obj.peek()}')