from unordered_linkedlist import ordered_list as ordered_list

olist = ordered_list.OrderedList()

olist.add(31)
olist.show()
print(f'HEAD is {olist.gethead()}')
olist.add(17)
olist.show()
olist.add(12)
olist.show()
olist.add(77)
olist.show()
olist.add(93)
olist.show()
olist.add(31)
olist.show()
olist.add(54)
olist.show()
print(olist.length())
olist.delete(100)
olist.show()
print(f"value popped is {olist.pop()}")
olist.show()
olist.push(24)
olist.show()
olist.show()
print(f' found 24 at index {olist.index(24)}')
print(f' found 81 at index {olist.index(81)}')
print(f' found 93 at index {olist.index(93)}')
print(f' found 101 at index {olist.index(101)}')
print(f' search 4 at index {olist.search(4)}')
