from unordered_linkedlist import unordered_list as unordered_list

ulist = unordered_list.UnorderedList()

ulist.add(31)
ulist.add(77)
ulist.add(17)
ulist.add(93)
ulist.add(26)
ulist.add(54)
ulist.show()
#print(ulist.length())
ulist.delete(100)
ulist.show()
print(f"value popped is {ulist.pop()}")
ulist.show()
ulist.push(24)
ulist.show()
ulist.append(55)
ulist.append(81)
ulist.show()
print(f' found 24 at index {ulist.index(24)}')
print(f' found 81 at index {ulist.index(81)}')
print(f' found 93 at index {ulist.index(93)}')
print(f' found 101 at index {ulist.index(101)}')
ulist.insert(0,0)
ulist.show()
ulist.insert(0,3)
ulist.show()
ulist.insert(0,9)
ulist.show()